package com.example.demo.model;

import java.util.ArrayList;
import java.util.List;

public class UserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public UserExample() {
		oredCriteria = new ArrayList<>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAdminNameIsNull() {
			addCriterion("admin_name is null");
			return (Criteria) this;
		}

		public Criteria andAdminNameIsNotNull() {
			addCriterion("admin_name is not null");
			return (Criteria) this;
		}

		public Criteria andAdminNameEqualTo(String value) {
			addCriterion("admin_name =", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameNotEqualTo(String value) {
			addCriterion("admin_name <>", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameGreaterThan(String value) {
			addCriterion("admin_name >", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameGreaterThanOrEqualTo(String value) {
			addCriterion("admin_name >=", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameLessThan(String value) {
			addCriterion("admin_name <", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameLessThanOrEqualTo(String value) {
			addCriterion("admin_name <=", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameLike(String value) {
			addCriterion("admin_name like", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameNotLike(String value) {
			addCriterion("admin_name not like", value, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameIn(List<String> values) {
			addCriterion("admin_name in", values, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameNotIn(List<String> values) {
			addCriterion("admin_name not in", values, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameBetween(String value1, String value2) {
			addCriterion("admin_name between", value1, value2, "adminName");
			return (Criteria) this;
		}

		public Criteria andAdminNameNotBetween(String value1, String value2) {
			addCriterion("admin_name not between", value1, value2, "adminName");
			return (Criteria) this;
		}

		public Criteria andHeadlineIsNull() {
			addCriterion("headline is null");
			return (Criteria) this;
		}

		public Criteria andHeadlineIsNotNull() {
			addCriterion("headline is not null");
			return (Criteria) this;
		}

		public Criteria andHeadlineEqualTo(String value) {
			addCriterion("headline =", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineNotEqualTo(String value) {
			addCriterion("headline <>", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineGreaterThan(String value) {
			addCriterion("headline >", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineGreaterThanOrEqualTo(String value) {
			addCriterion("headline >=", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineLessThan(String value) {
			addCriterion("headline <", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineLessThanOrEqualTo(String value) {
			addCriterion("headline <=", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineLike(String value) {
			addCriterion("headline like", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineNotLike(String value) {
			addCriterion("headline not like", value, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineIn(List<String> values) {
			addCriterion("headline in", values, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineNotIn(List<String> values) {
			addCriterion("headline not in", values, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineBetween(String value1, String value2) {
			addCriterion("headline between", value1, value2, "headline");
			return (Criteria) this;
		}

		public Criteria andHeadlineNotBetween(String value1, String value2) {
			addCriterion("headline not between", value1, value2, "headline");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table admin
	 * @mbg.generated  Thu Jun 25 12:23:51 CST 2020
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table admin
     *
     * @mbg.generated do_not_delete_during_merge Sun Mar 22 16:48:50 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}