package com.example.demo.DTO;

import lombok.Data;

@Data
public class BlogsDTO {
	 private Integer id;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column blogs.headline
	     *
	     * @mbg.generated Sun Mar 22 16:48:50 CST 2020
	     */
	    private String headline;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column blogs.introduce
	     *
	     * @mbg.generated Sun Mar 22 16:48:50 CST 2020
	     */
	    private String introduce;

	    /**
	     *
	     * This field was generated by MyBatis Generator.
	     * This field corresponds to the database column blogs.time
	     *
	     * @mbg.generated Sun Mar 22 16:48:50 CST 2020
	     */
	    private String time;
	    private String imgUrl;
}
